# Generated by Django 3.1.7 on 2021-03-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=128)),
                ('artist_name', models.CharField(max_length=128)),
                ('artwork_url', models.URLField()),
                ('line_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lineuser')),
            ],
        ),
    ]
