# Generated by Django 3.1.7 on 2021-03-19 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
