# Generated by Django 3.1.7 on 2021-03-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuser',
            name='stop',
            field=models.BooleanField(default=False),
        ),
    ]
